polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # url example: /polls/
    path('', views.index, name='index'),

    # url example: /polls/1/
    path('<int:question_id>/', views.detail, name='detail'),

    # url example: /polls/1/results/
    path('<int:question_id>/results/', views.results, name='results'),

    # url example: /polls/1/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

sample_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/models.py
import datetime


from django.db import models
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    DOB = models.DateField(default=datetime.date.today())
    pub_date = models.DateTimeField('date published')
    age = models.IntegerField(default = 18)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, Http404

from django.template import loader
from django.shortcuts import render, get_object_or_404


from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('pub_date')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

    #return HttpResponse("Hello, world. You're at the polls index.")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

polls/templates/polls/detail.html
<h1>Name: {{ question.question_text }}</h1>
<ul>
  <li>Age: {{question.age}}</li>
  <li>Date of Birth: {{question.DOB}}</li>
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <table>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>DOB</th>
      </tr>
      {% for question in latest_question_list %}
      <tr>
          <td><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></td>
          <td>{{question.age}}</td>
          <td>{{question.DOB}}</td>
      </tr>
      {% endfor %}
    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}